name: native_app_shell_mobile
description: Native App Shell for UI Builder applications

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^8.1.6
  flutter_inappwebview: ^6.1.0+1
  url_launcher: ^6.3.0
  backendless_sdk: ^8.0.0-alpha.28
  overlay_support: ^2.0.1
  geolocator: ^8.0.5
  sign_in_with_apple: ^6.1.2
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^7.1.1
  app_links: ^6.3.2
  path_provider: ^2.0.12
  package_info_plus: ^8.0.2
  share_plus: 7.0.2
  flutter_contacts: ^1.1.7+1
  syncfusion_flutter_pdfviewer: ^27.1.50
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  sensors_plus: ^4.0.2
  pay: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  win32: ^5.5.4
  url_launcher_ios: ^6.3.1
  flutter_local_notifications: ^17.2.3

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/ui_builder_app/
    - assets/ui_builder_app/library/sdk/
    - assets/ui_builder_app/libs/less/
    - assets/ui_builder_app/libs/material-ui-icons/
    - assets/ui_builder_app/libs/require/
    - assets/ui_builder_app/library/sdk/modules/

  fonts:
    - family: CustomAssets
      fonts: