name: native_app_shell_mobile
description: Native App Shell for UI Builder applications

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^8.1.6
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.0.10
  backendless_sdk: ^8.0.0-alpha.25
  overlay_support: ^2.0.1
  audioplayers: ^5.1.0
  geolocator: ^8.0.5
  sign_in_with_apple: ^3.3.0
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^5.0.7
  uni_links: ^0.5.1
  path_provider: ^2.0.12
  package_info_plus: ^3.0.2
  share_plus: 7.0.2
  contacts_service: ^0.6.3
  syncfusion_flutter_pdfviewer: ^21.2.10
  firebase_core: ^2.7.0
  firebase_messaging: ^14.7.10
  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/notification_sounds/push_sound.wav
    - assets/ui_builder_app/
    - assets/ui_builder_app/library/sdk/
    - assets/ui_builder_app/libs/less/
    - assets/ui_builder_app/libs/material-ui-icons/
    - assets/ui_builder_app/libs/require/
    - assets/ui_builder_app/library/sdk/modules/

  fonts:
    - family: CustomAssets
      fonts: